{
 "title": "IoT FleetWise - Tesla3",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://i.piano.io/managedservices/the-brussels-times/tesla-picture.png\">\n"
   }
  },
  {
   "title": "Range",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Powertrain.Range",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double)  FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\norder by bin(time,$__interval) asc",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "SoC",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Powertrain.TractionBattery.StateOfCharge.Displayed",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::bigint)  FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\norder by bin(time,$__interval) asc",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "SoC (used)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Powertrain.TractionBattery.StateOfCharge.Displayed",
     "rawQuery": "SELECT \nmax(measure_value::bigint)  \n- min(measure_value::bigint) \nFROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\n\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Speed (Current)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Speed",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, \nbin(time,$__interval), max(measure_value::double)  FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\norder by bin(time,$__interval) asc",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "kWh Used",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Powertrain.TractionBattery.AccumulatedChargedEnergy",
     "rawQuery": "SELECT vehicleName, campaignName, \n\nbin(time,$__interval),\n/*\nmax(\n  case when measure_name ='Vehicle.Battery.CurrentCurrent' then\n  measure_value::double\n  end\n) *\nmax(\n  case when measure_name ='Vehicle.Battery.CurrentVoltage' then\n  measure_value::double\n  end\n)   * 100/ 1000 kwh_per_100km,\n*/\nmax(\n  case when measure_name ='Vehicle.Battery.CurrentCurrent' then\n  measure_value::double\n  end\n) *\nmax(\n  case when measure_name ='Vehicle.Battery.CurrentVoltage' then\n  measure_value::double\n  end\n) * to_milliseconds( $__interval) / 1000 / 3600 / 1000 kWh\n FROM $__database.$__table \nwhere measure_name in ( 'Vehicle.Battery.CurrentCurrent' ,'Vehicle.Battery.CurrentVoltage')\nand $__timeFilter\t\ngroup by 1,2,3\norder by bin(time,$__interval) asc",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Odometry",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.TraveledDistance",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, \nbin(time,$__interval), max(measure_value::double)  FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": {
    "content": "<br/><br/><img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/HCLTech-new-logo.svg/306px-HCLTech-new-logo.svg.png?20220926142743\">\n"
   }
  },
  {
   "title": "Average Speed",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Speed",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double) speed FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    },
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Chassis.Accelerator.PedalPosition",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double) pedal_pos  FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.CurrentLocation.Latitude",
     "rawQuery": "SELECT vehicleName, campaignName, \nbin(time,$__interval), \navg(case when measure_name = 'Vehicle.CurrentLocation.Latitude' then \nmeasure_value::double\nend) latitude,\navg(case when measure_name = 'Vehicle.CurrentLocation.Longitude' then \nmeasure_value::double\nend) Longitude\n\nFROM \"ts-tesla3\".VehicleDataTable\nwhere measure_name like 'Vehicle.CurrentLocation.L%'\nand $__timeFilter\t\ngroup by 1,2,3\n\n order by 4 desc  \n ",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "Wheel Angle and Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Chassis.SteeringWheel.Angle",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double) angle FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    },
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Chassis.SteeringWheel.Speed",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double) speed  FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  },
  {
   "title": "EOP (actual and expected)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "targets": [
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Powertrain.EOP",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double) EOP FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    },
    {
     "database": "\"ts-tesla3\"",
     "measure": "Vehicle.Powertrain.EOPExpected",
     "rawQuery": "SELECT vehicleName, campaignName, measure_name, bin(time,$__interval), max(measure_value::double) EOP_expected FROM $__database.$__table \nwhere measure_name = '$__measure'\nand $__timeFilter\t\ngroup by 1,2,3, 4\n",
     "table": "\"VehicleDataTable\""
    }
   ]
  }
 ]
}